### ISSUE TITLE
Demo 2

### ISSUE THREAD

**Issue by AmirZV** [mohammadrezza/Kiruna-eXplorer#26]
I believe you did a great job overall.
The home page is minimalistic and beautiful.
The ability to edit documents is very useful.

I do have a few suggestions for improvement:
- On the document page, using a better color palette could enhance the user's ability to distinguish between different page elements.
- The styling of elements on the login page could be improved by adjusting their positioning.

Thank you all!

**Comment by s330029** [comment]
Thank you for your feedback and kind words! 
We truly appreciate your suggestions and will work on improving the design and user experience further.
